[versions]
kodeinDi = "7.23.1"
firebaseAuth = "2.1.0"
kotlinxCoroutinesCore = "1.9.0"
kotlinxSerializationJson = "1.7.3"
kotlin = "2.1.0"

[libraries]
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebaseAuth" }
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodeinDi" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

